- edx_event_bus_kafka/management/commands/produce_event.py
- edx_event_bus_kafka/publishing/event_producer.py
I believe a nullary call to poll uses a default timeout of -1 (wait
indefinitely), but we really just want to make sure that pending callbacks
are triggered for the acks that have been buffered in the background, from
previous events. poll(0) will not block if the buffer is empty.
For testing we need to call flush(-1), so add sync=True as an option.
Documentation for `rd_kafka_poll`:
https://github.com/edenhill/librdkafka/blob/4faeb8132521da70b6bcde14423a14eb7ed5c55e/src/rdkafka.h#L3079
This addresses part of https://github.com/openedx/event-bus-kafka/issues/10
> fix: Use non-blocking poll after production; allow flush for testing

- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/consumer/event_consumer.py
- edx_event_bus_kafka/consumer/tests/test_event_consumer.py
**Description:** This adds the ability to specify any signal to emit
from messages that are pulled from the message queue.
If the message's signal type doesn't match the signal
type specified to the command, that message is dropped.
This also refactors some of the code to help track state.
**JIRA:** [Link to JIRA ticket](https://github.com/openedx/event-bus-kafka/issues/4)
**Testing instructions:**
1. Run `make test`
**Reviewers:**
**Post merge:**
finished.
**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.
> feat: Specify signals to consumer management command.

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/config.py
- edx_event_bus_kafka/publishing/event_producer.py
- edx_event_bus_kafka/publishing/test_event_producer.py
Deduplicating configuration into config file
The config file is mostly the same as the common-config given, null checks are added in to the get_producer function in order to accomodate these functions on a separate file. 
@timmc-edx when you wrote the override_settings in the test file did you intend for the name of the settings (SCHEMA_REGISTRY_URL for example) to not have EVENT_BUS_KAFKA before it? I couldn't make the tests run as intended without the EVENT_BUS_KAFKA in front of it.
> feat: Deduplicate config

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/consumer/event_consumer.py
- edx_event_bus_kafka/consumer/tests/test_event_consumer.py
We also refactor the consumer to use a common config.
https://github.com/openedx/event-bus-kafka/issues/15
> refactor: Consumer uses the same config loading as producer.

- CHANGELOG.rst
- README.rst
- docs/how_tos/manual_testing.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/consumer/README.rst
- edx_event_bus_kafka/consumer/event_consumer.py
- edx_event_bus_kafka/consumer/tests/test_event_consumer.py
- edx_event_bus_kafka/publishing/test_event_producer.py
This changes `KAFKA_CONSUMERS_ENABLED` and `CONSUMER_POLL_TIMEOUT` and
updates documentation and tests for other settings.
> feat!: Ensure all settings have consistent `EVENT_BUS_KAFKA_` prefix

- .github/PULL_REQUEST_TEMPLATE.md
I notice that people largely ignore PR templates, *especially* big ones.
I think that shrinking this down to just the essentials will increase the
likelihood that people use it.
In particular, I want to remove things like "All reviewers approved" and
"CI build is green" that are generally already enforced by repo policies,
"Delete working branch" (there's a setting for that if we want it!), and
release instructions (should be in a central document linked from the
README).
> docs: Update PR template to something people might actually use

- docs/decisions/0005-optional-import-of-confluent-kafka.rst
- edx_event_bus_kafka/config.py
- edx_event_bus_kafka/consumer/event_consumer.py
- edx_event_bus_kafka/consumer/tests/test_event_consumer.py
- edx_event_bus_kafka/publishing/event_producer.py
- edx_event_bus_kafka/publishing/test_event_producer.py
Explain reasoning in ADR 5 and link to it from try-imports. Also, fix some
rST syntax and the ADR title.
> test: Leave confluent_kafka imports undefined in tests

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/publishing/event_producer.py
- edx_event_bus_kafka/publishing/test_event_producer.py
This should close out https://github.com/openedx/event-bus-kafka/issues/16
by just embracing the use of multiple producers.
Also:
- Improve cache-clearing during tests by connecting to the setting_changed
signal -- this allows knowledge of what's cached to be local to the
module where the caching happens, rather than relying on each test module
to know about all of the modules it depends on indirectly.
- Remove outdated comment about caching, and clarify other caching
comments.
> feat: Never evict producers from cache

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/config.py
- edx_event_bus_kafka/consumer/event_consumer.py
- edx_event_bus_kafka/management/commands/produce_event.py
- edx_event_bus_kafka/publishing/event_producer.py
- edx_event_bus_kafka/publishing/test_event_producer.py
- edx_event_bus_kafka/tests/test_config.py
Purpose:
- Revisit https://github.com/openedx/event-bus-kafka/issues/16 since I finally figured out a clean way to have a single producer.
- Reduce the burden on future code that will need to adjust how polling is done (https://github.com/openedx/event-bus-kafka/issues/31) and maybe handle shutdown (https://github.com/openedx/event-bus-kafka/issues/11)
- Prepare for configurable implementation loading, which will need a singleton and getter: https://github.com/openedx/openedx-events/issues/87
- Get rid of the `sync` argument (which didn't fit the abstraction) and move it to a dedicated method.
Relying code should now call `get_producer().send(...)` rather than `send_to_event_bus(...)`. The return value is an object that wraps a `Producer` instance (not a `SerializingProducer`) and that …
> feat!: Switch to a single Producer, wrapped in an API singleton

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/consumer/tests/test_event_consumer.py
- edx_event_bus_kafka/management/commands/consume_events.py
- edx_event_bus_kafka/management/commands/produce_event.py
Pylint wasn't checking these modules since they weren't importable
packages, due to the missing init files.
> style: Add missing `__init__.py` files and fix lint issues

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/config.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/producer.py
- edx_event_bus_kafka/internal/tests/test_config.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
- edx_event_bus_kafka/internal/tests/test_producer.py
Closes https://github.com/openedx/event-bus-kafka/issues/35
Also add missing test for consume-loop.
> feat: Add topic prefix when configured (EVENT_BUS_TOPIC_PREFIX)

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/producer.py
- edx_event_bus_kafka/internal/tests/test_producer.py
Two changes, though I can be convinced to split them out.
First makes KafkaEventConsumer public
Second renames EventProducerKafka to KafkaEventProducer to be consistent.
> feat!: add KafkaEventConsumer to public API

- CHANGELOG.rst
- edx_event_bus_kafka/internal/consumer.py
New Relic released an update that handles message consumption transactions, and this logging was redundant.
Also, it didn't work.
> feat: Remove background_task decorator.

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
This was originally intended as a rollout switch, but running the consumer already requires invoking a management command. Defaulting to True makes this an emergency kill-switch, which is more plausibly useful.
Remove ticket link that is now outdated.
> feat: Change `EVENT_BUS_KAFKA_CONSUMERS_ENABLED` default to True

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
Doing this separately to bring in a change to the COURSE_CATALOG_INFO_CHANGED event schema. The schema is generated and sent to Kafka by code in this repository, so in order to actually start using any schema changes we need to upgrade this library first. 
> feat: upgrade openedx-events to 3.0.0

- CHANGELOG.rst
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
The consumer is configured with a signal to listen for, and while the `emit_signals_from_message` was validating that messages matched the signal, it was then doing a lookup on the event type anyhow. I think this was harmless but redundant, so this removes that lookup.
Also, improve consumer tests, mostly by adding assertions on logging (done as a separate commit, but will be squashed.)
> fix: Don't look up signal a second time in consumer

- CHANGELOG.rst
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/producer.py
- edx_event_bus_kafka/internal/tests/test_producer.py
This should not cause any change in behavior -- it just pins the existing behavior as explicit and adds a comment explaining it.
> fix: Explicitly encode message header values as UTF-8

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
New consumers will only processes messages that have been added to the topic since the consumer group was spun up. This will prevent new consumers from trying to process a massive backlog of events that have been publishing for a while.
> feat: start processing messages at latest offset

- CHANGELOG.rst
- docs/decisions/0008-baseline-error-handling-for-producer.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/producer.py
- edx_event_bus_kafka/internal/tests/test_producer.py
Include all event data when logging errors in producing so if necessary dropped events can be replayed from the logs.
Issue: https://github.com/openedx/event-bus-kafka/issues/45
> feat: log full event data on all errors in producing

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/producer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
Issue: https://github.com/openedx/event-bus-kafka/issues/72
Also changes BaseException to Exception when error handling to avoid catching things like KeyboardInterrupt or SystemExit.
> feat: manually commit every message on consumption

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
Also includes a foundational commit for improving testing of the signal/receivers.
This is part of https://github.com/openedx/event-bus-kafka/issues/62
> feat: Log warning in consumer when receivers fail with error

- docs/how_tos/manual_testing.rst
- edx_event_bus_kafka/internal/consumer.py
- Split out producer/consumer testing into separate sections
- Put consumer before producer to increase chance of success.
(Mention topic creation issue.)
- Remove Django settings -- these are now in `cms/envs/devstack.py`
- Put both rsync mentions together
- Fix top heading
> docs: Update manual testing doc: consumer first; separate halves; rm settings

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
This will aid in error recovery -- if we need to replay a chunk of the
topic, we'll need to have partition and offset information in the logs.
The thrown exception is given its own class in order to help with building
alerts that can discriminate between different sources of errors (business
logic unique to the consuming IDA vs. more generic kafka/avro issues).
This is part of https://github.com/openedx/event-bus-kafka/issues/62
> feat: Log and record receiver errors the same way as other errors

- docs/decisions/0008-baseline-error-handling-for-producer.rst
- docs/decisions/0009-baseline-error-handling-for-consumer.rst
This reflects how our handling of receiver errors changed a bit in commit 0f0874ce51dd/PR #82.
This is part of https://github.com/openedx/event-bus-kafka/issues/62
> docs: Update error-handling ADRs; mark as accepted

- CHANGELOG.rst
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
In the case where we would want to replay events,
we would need to change the offsets in the partitions so that we can consume from an earlier point. This allows users to pass in a new offset parameter that will reset the offsets before starting to consume again.
https://github.com/edx/edx-arch-experiments/issues/115
> feat: Add the ability to override offsets.

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
Kill infinite consumer loop when we see a fatal KafkaError, as recommended in the documentation. See
https://github.com/confluentinc/librdkafka/blob/e0b9e92a0b492b5b1a6f1bcf08744928d45bf396/INTRODUCTION.md#fatal-consumer-errors
Task: https://github.com/edx/edx-arch-experiments/issues/139
> feat: kill consumer loop on fatal errors

- CHANGELOG.rst
- README.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
This is intended to help with a stuck DB connection issue we observed:
https://github.com/edx/edx-arch-experiments/issues/144
PR is divided into two commits; first commit is a small testing refactor (extraction of a helper).
> feat: Allow exiting consumer if too many errors in a row

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
We have been seeing strange behavior when trying to reset the offsets in Kafka for replay. This should simplify the behavior of the event bus when we are trying to reset the offsets on the event bus.
https://github.com/openedx/event-bus-kafka/issues/107
> feat: Do not consume events when in replay mode.

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
We believe that the offsets are not reset and assigned until poll is called. This poll should not process events or commit the offsets with the messages it returns.
> fix: Added poll call to reset-offset code.

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
We were using the incorrect command to set the offsets. commit is the correct one and assign was the incorrect one.
> fix: Commit offsets instead of assigning them.

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
The goal here is just to split out the two fairly unrelated pieces of functionality of consuming vs. resetting, especially since the reset code no longer does any consuming. (A linter was also starting to get testy about how large the method was.)
This deprecates the `offset_timestamp` parameter to the existing `consume_indefinitely` method; callers should switch to using the new method. After course-discovery is updated to use it, can remove the parameter.
> feat: Refactor consume-loop, adding `reset_offsets_indefinitely` method

- CHANGELOG.rst
- README.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
Also note the "manual" dependency issue in the README.
This check is already present in course-discovery's copy of the command.
> fix: Log helpful error if confluent_kafka is not installed

- CHANGELOG.rst
- README.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/producer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
- edx_event_bus_kafka/internal/tests/test_producer.py
- edx_event_bus_kafka/internal/tests/test_utils.py
- edx_event_bus_kafka/internal/utils.py
- requirements/base.in
Issue: https://github.com/openedx/openedx-events/issues/162
Pass all EventsMetadata fields as headers when producing an event to Kafka. The consumer takes these headers and emits the signal with the original metadata, as reconstructed from the message headers.
To prevent the need for lock-step upgrades, all headers except event type and id are considered optional. If not passed, we will just use the default value in EventsMetadata. This is why _get_metadata_from_headers returns and EventsMetadata object instead of just a dictionary of kwargs to pass to `send_event_with_custom_metadata`. 
We can make another ticket to make the other headers mandatory after and possibly rethink what _get_metadata_from_headers returns. 
> feat: emit original headers with message

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
This just follows a breaking API change in openedx-events and should not have any impact on dependents.
Pending:
> fix: Use openedx-events 5.0.0 and new custom-metadata method signature

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/config.py
- edx_event_bus_kafka/internal/consumer.py
Addresses https://github.com/openedx/event-bus-kafka/issues/124
> docs: Add docs for all Django settings

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/producer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
- edx_event_bus_kafka/internal/tests/test_producer.py
- edx_event_bus_kafka/internal/tests/test_utils.py
`evt.headers()` turns out to be unpopulated, so use the bound context data
instead. Addresses https://github.com/openedx/event-bus-kafka/issues/128
Also:
- Move some test utilities out of the consumer tests and into test_utils.py (separate commit)
- Use FakeMessage rather than mock
- Fix previous release's date in changelog
> fix: Include message_id correctly in producer audit log

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
- requirements/base.in
Issue: https://github.com/openedx/event-bus-kafka/issues/135
Blocked on https://github.com/openedx/openedx-events/pull/187
> fix: load all signals in consume_events

- requirements/ci.in
- requirements/ci.txt
- requirements/dev.txt
Already using the GitHub Action (of the latest version).
https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259
> fix: Remove yanked codecov package

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
Issue: https://github.com/openedx/openedx-events/issues/78
When consuming events, determine the correct signal to use from the message header rather than an argument passed into the management command. This is a necessary step towards allowing multiple event types on a single topic.
Temporarily makes the `signal` argument optional so it can be safely removed from callers without needing a lockstep upgrade. After we are reasonably certain we have upgraded any processes using the management command, we can make the breaking change and do a major version upgrade.
Also, since Consumer.poll() may return a message with an error object, remove misleading documentation saying it can't. DeserializingConsumer turned those errors into exceptions but the plain Consumer will keep them as errors on the …
> feat: determine signal from message header

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
Re-add the 'signal' parameter to the KafkaEventConsumer, as is expected by the EventBusConsumer API.
> fix: add signal back as optional param

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/producer.py
- edx_event_bus_kafka/internal/tests/test_producer.py
Update serializers to allow multiple event types per topic. See https://docs.openedx.org/projects/event-bus-kafka/en/latest/decisions/0011_multiple_event_types_per_topic.html for the full explanation of why.
> feat: use topic record name strategy

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/producer.py
- edx_event_bus_kafka/internal/tests/test_producer.py
Adds event_data_as_json to the error log when an event is not published. This will make it easier to recreate the event from the logs using an AvroSignalDeserializer.
Added the field instead of replacing the event data field so we will still get the event that was passed to the send method even if something in the serializer throws an error on creation. Also left everything else in the `=` format because Splunk is actually parsing them correctly as fields, it was just the nested event data it had trouble with. 
To test, set up your event bus to point to the dev cluster but with an incorrect schema registry password. When trying to fire an event, you should see an error like 
``
Error delivering message to Kafka event bus. error=Unauthorized (HTTP status code 401, SR code 401) …
> feat: add json-formatted event data to error logs

- CHANGELOG.rst
- Makefile
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/producer.py
- edx_event_bus_kafka/internal/tests/test_producer.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
Add metadata in json form to the error logs when events fail to publish. This will be useful for republishing the events later.
Issue: 
https://github.com/edx/edx-arch-experiments/issues/354
> feat: add event metadata as json to publish error logs

- CHANGELOG.rst
- edx_event_bus_kafka/internal/producer.py
In error logging, we did not have the full_topic
available for searching/alerting because of the order in which these assignments happened. Reordering them to try to ensure we always get the full_topic in context.
https://github.com/edx/edx-arch-experiments/issues/411
> fix: Reorder context assignment in producer code.

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/producer.py
In the past, we used generic exceptions to record errors to New Relic. This creates custom exceptions for producing and consuming so that we can query New Relic on custom exceptions instead of relying on log messages.
https://github.com/edx/edx-arch-experiments/issues/389
> feat: Use custom exceptions for recording errors.

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/config.py
- edx_event_bus_kafka/internal/tests/test_config.py
Allows configuring of the client id of producers and consumers so we can better track our message streams.
> feat: add configurable client.id to base settings

- CHANGELOG.rst
- edx_event_bus_kafka/internal/config.py
- edx_event_bus_kafka/internal/tests/test_config.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
Use the new method in openedx-events instead of accessing the settings directly
> fix: use new method for setting client id

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
Moved function_trace call to a higher level to capture more information about the overall inner loop of the consumer. Also renamed the function trace to ``consumer.consume`` so it's clearer from the outside what the span is doing.
> fix: Add monitoring information inside the function trace.

- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
New custom metric `kafka_received_message` added to span contexts.
> feat: Add custom metric to track whether a message processed.

- .coveragerc
- CHANGELOG.rst
- edx_event_bus_kafka/__init__.py
- edx_event_bus_kafka/internal/consumer.py
- edx_event_bus_kafka/internal/tests/test_consumer.py
- PR created under the issue https://github.com/edx/edx-arch-experiments/issues/785
- Added custom `dajngo_version` and `python_version` attributes recording within the kafka workers.
> build: set custom django and python versions in kafka workers
