README.rst

**Description:**
Update README to note that upgrading will
likely need to be manual for this dependency,
which is likely to be a private dependency.

docs: update README for upgrading

---

CHANGELOG.rst
edx_event_bus_kafka/__init__.py
edx_event_bus_kafka/consumer/tests/test_event_consumer.py

test: Fix import exception class name

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

chore: Upgrade Python dependencies

---

CHANGELOG.rst
edx_event_bus_kafka/__init__.py
edx_event_bus_kafka/internal/producer.py
edx_event_bus_kafka/internal/tests/test_config.py
edx_event_bus_kafka/internal/tests/test_producer.py

Addresses https://github.com/openedx/event-bus-kafka/issues/31
Also an unrelated commit to fix some minor test issues I encountered.

feat: Poll producer on a regular cadence to avoid delayed callbacks

---

docs/decisions/0007-producer-polling.rst
edx_event_bus_kafka/internal/producer.py

docs: Add ADR for polling loop

---

.github/workflows/upgrade-python-requirements.yml

Issue: #34
This PR adds the requirement upgrade workflow to the repository. The workflow will be run automatically on Tuesday 2:00am every week.

build: add upgrade requirement workflow

---

.github/workflows/ci.yml
.github/workflows/pypi-publish.yml

chore: Upgrade versions of GitHub actions

---

openedx.yaml

build: this repo is not part of Open edX releases

---

CHANGELOG.rst
edx_event_bus_kafka/__init__.py
edx_event_bus_kafka/internal/consumer.py

In order to have New Relic monitoring of event handling/processing, we are adding a decorator to the handling of single events.
https://github.com/edx/edx-arch-experiments/issues/70

feat: Add monitoring to consumption tasks.

---

CHANGELOG.rst
README.rst
edx_event_bus_kafka/__init__.py
edx_event_bus_kafka/internal/consumer.py
edx_event_bus_kafka/management/commands/produce_event.py

docs: Ensure TODOs have ticket links as necessary

---

CHANGELOG.rst
edx_event_bus_kafka/__init__.py
edx_event_bus_kafka/internal/consumer.py

fix: Remove proof-of-concept code that logs user-login events

---

CHANGELOG.rst
edx_event_bus_kafka/__init__.py
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

See https://github.com/openedx/openedx-events/pull/138 for the fix being brought in

feat: upgrade openedx-events and fastavro

---

CHANGELOG.rst
edx_event_bus_kafka/__init__.py
edx_event_bus_kafka/internal/consumer.py
edx_event_bus_kafka/internal/producer.py

Also add comments, fix lint issue.

feat: Commit consumer offset asynchronously

---

docs/decisions/0002-kafka-based-event-bus.rst
docs/decisions/0003-managing-kafka-consumers.rst
docs/decisions/0004-kafka-managed-hosting.rst

This is in support of https://github.com/edx/edx-arch-experiments/issues/116

docs: mark appropriate ADRs as accepted

---

CHANGELOG.rst
edx_event_bus_kafka/__init__.py
edx_event_bus_kafka/internal/producer.py
edx_event_bus_kafka/internal/tests/test_producer.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

- [N/A] Commits are squashed
- [N/A] Noted any: Concerns, dependencies, deadlines, tickets, testing instructions

feat!: make event_metadata a required parameter of send()

---

edx_event_bus_kafka/__init__.py

fix: Update version number.

---

docs/how_tos/manual_testing.rst

docs: How to produce an event via Studio

---

CHANGELOG.rst
edx_event_bus_kafka/__init__.py
edx_event_bus_kafka/internal/consumer.py
edx_event_bus_kafka/internal/tests/test_consumer.py

Use the full version of the topic when finding offsets.
Fix argument handling for the example management command.
Bump version.

fix: Use the correct version of the topic.

---

edx_event_bus_kafka/internal/consumer.py
edx_event_bus_kafka/internal/tests/test_consumer.py

Note: This is intended to merge to another branch and then be squashed in that branch.

fixup! simplify reconnect code

---

CHANGELOG.rst
edx_event_bus_kafka/internal/consumer.py

docs: Clarify/update some comments

---

CHANGELOG.rst
edx_event_bus_kafka/__init__.py

I tried to release v3.9.0 but I hadn't bumped the version...

fix: Fix the version and changelog

---

CHANGELOG.rst
edx_event_bus_kafka/__init__.py
edx_event_bus_kafka/internal/consumer.py

Adds New Relic function traces to better track
the amount of time we are spending in different parts of our consumption flow.

feat: Add more monitoring to consumption workflow.

---

CHANGELOG.rst
docs/how_tos/manual_testing.rst
edx_event_bus_kafka/__init__.py
edx_event_bus_kafka/internal/consumer.py
edx_event_bus_kafka/internal/tests/test_consumer.py
edx_event_bus_kafka/management/commands/consume_events.py
requirements/base.in
test_settings.py

**Dependencies** 
- https://github.com/openedx/openedx-events/pull/200

feat: make use of abstract consumer API

---

README.rst

docs: Update config docs in README for new Consumer API

---

docs/decisions/0011_multiple_event_types_per_topic.rst

Add additional note on how consumers find the schema.

feat: add note to 0011_multiple_event_types_per_topic.rst
